version: '3.5'

services:
  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  jupyter_mongo:
    build:
      context: ./jupyter/
    ports:
      - 8888:8888
    restart: always
    environment:
      JUPYTER_TOKEN: "Session21"
    volumes:
        - ../:/Session21/Day2
    depends_on:
      - mongo
    links:
      - mongo
