version: '3.5'

services:
  postgres:
    image: postgres:14
    restart: always
    # Optional: Map the container port to a host port to be able to connect with a local db client 
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_DJANGO_NAME=${DB_DJANGO_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ../IMDB-directors.csv:/docker-entrypoint-initdb.d/IMDB-directors.csv
      - ../IMDB-movies.csv:/docker-entrypoint-initdb.d/IMDB-movies.csv
      - ../IMDB-movies_directors.csv:/docker-entrypoint-initdb.d/IMDB-movies_directors.csv
      - ../IMDB-movies_genres.csv:/docker-entrypoint-initdb.d/IMDB-movies_genres.csv
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:6.11
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  jupyter:
    build:
      context: ./jupyter/
    ports:
      - 8888:8888
    environment:
      - PGSERVICEFILE=${PGSERVICEFILE}
      - PGPASSFILE=${PGPASSFILE}
    restart: always
    environment:
      JUPYTER_TOKEN: "Session21"
    volumes:
        - ../:/Session21/Day2
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin:
