# Generated by Django 5.0.6 on 2024-06-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbDirectors',
            fields=[
                ('director_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imdb_directors',
            },
        ),
        migrations.CreateModel(
            name='ImdbMovies',
            fields=[
                ('movie_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imdb_movies',
            },
        ),
        migrations.CreateModel(
            name='ImdbMoviesDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.imdbdirectors')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.imdbmovies')),
            ],
            options={
                'db_table': 'imdb_movies_directors',
            },
        ),
        migrations.CreateModel(
            name='ImdbMoviesGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(blank=True, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.imdbmovies')),
            ],
            options={
                'db_table': 'imdb_movies_genre',
            },
        ),
    ]
